swagger: '2.0'
info:
  title: Item Example API
  version: "0.1"
consumes:
  - servicelication/json
produces:
  - servicelication/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /items:
    get:
      tags: [Items]
      operationId: ringo_service.api.search
      summary: Get all items
      parameters:
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
      responses:
        200:
          description: Return items
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    post:
      tags: [Items]
      operationId: ringo_service.api.create
      summary: Create a item
      parameters:
        - name: item
          in: body
          schema:
            $ref: '#/definitions/Item'
      responses:
        201:
          description: New item created
  /items/{item_id}:
    get:
      tags: [Items]
      operationId: ringo_service.api.read
      summary: Get a single item
      parameters:
        - $ref: '#/parameters/item_id'
      responses:
        200:
          description: Return item
          schema:
            $ref: '#/definitions/Item'
        404:
          description: Item does not exist
    put:
      tags: [Items]
      operationId: ringo_service.api.update
      summary: Update a item
      parameters:
        - $ref: '#/parameters/item_id'
        - name: item
          in: body
          schema:
            $ref: '#/definitions/Item'
      responses:
        200:
          description: Item updated
    delete:
      tags: [Items]
      operationId: ringo_service.api.delete
      summary: Remove a item
      parameters:
        - $ref: '#/parameters/item_id'
      responses:
        204:
          description: Item was deleted
        404:
          description: Item does not exist


parameters:
  item_id:
    name: item_id
    description: Item's Unique identifier
    in: path
    type: integer
    required: true

${definitions}

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
